#!/usr/bin/env python3
import argparse
import json
import os
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


def sh(cmd: List[str]) -> str:
    return subprocess.check_output(cmd, text=True, stderr=subprocess.STDOUT).strip()


@dataclass(frozen=True)
class Nic:
    name: str
    mac: str
    ipv4: List[str]


def list_nics() -> List[Nic]:
    out = sh(["ip", "-j", "addr", "show"])
    data = json.loads(out)
    nics: List[Nic] = []
    for iface in data:
        name = iface.get("ifname", "")
        if not name or name == "lo":
            continue
        mac = iface.get("address") or ""
        ipv4: List[str] = []
        for ai in iface.get("addr_info", []) or []:
            if ai.get("family") == "inet":
                local = ai.get("local")
                prefixlen = ai.get("prefixlen")
                if local and prefixlen is not None:
                    ipv4.append(f"{local}/{prefixlen}")
        nics.append(Nic(name=name, mac=mac, ipv4=ipv4))
    return nics


def _bind(s: Any) -> Optional[str]:
    if s is None:
        return None
    v = str(s).strip()
    return v or None


def _req_str(v: Any, name: str) -> str:
    s = _bind(v)
    if not s:
        raise SystemExit(f"Missing required field: {name}")
    return s


def _req_int(v: Any, name: str) -> int:
    try:
        return int(v)
    except Exception:
        raise SystemExit(f"Invalid integer for {name}")


def _match_nic(nics: List[Nic], match: Dict[str, Any]) -> Nic:
    want_if = _bind(match.get("interface"))
    want_mac = _bind(match.get("mac"))
    candidates = nics
    if want_if:
        candidates = [n for n in candidates if n.name == want_if]
    if want_mac:
        want_mac_l = want_mac.lower()
        candidates = [n for n in candidates if (n.mac or "").lower() == want_mac_l]
    if len(candidates) == 1:
        return candidates[0]
    if not candidates:
        raise SystemExit(f"No NIC matched interface={want_if!r} mac={want_mac!r}")
    raise SystemExit(
        "Multiple NICs matched; specify interface and/or mac more precisely: "
        + ", ".join(f"{n.name}({n.mac})" for n in candidates)
    )


def _validate_ipv4(ip: str) -> None:
    if not re.match(r"^\d{1,3}(\.\d{1,3}){3}$", ip):
        raise SystemExit(f"Invalid IPv4 address: {ip}")


def _render_netplan_yaml(
    *,
    control: Tuple[Nic, Dict[str, Any]],
    avoip: Optional[Tuple[Nic, Dict[str, Any]]],
) -> str:
    (ctrl_nic, ctrl_cfg) = control

    def iface_block(nic: Nic, cfg: Dict[str, Any]) -> List[str]:
        ipv4 = cfg["ipv4"]
        addr = _req_str(ipv4.get("address"), "ipv4.address")
        prefix = _req_int(ipv4.get("prefix"), "ipv4.prefix")
        gw = _bind(ipv4.get("gateway"))
        dns = ipv4.get("dns") or []
        _validate_ipv4(addr)
        lines: List[str] = []
        lines.append(f"    {nic.name}:")
        lines.append("      dhcp4: false")
        lines.append(f"      addresses: [{addr}/{prefix}]")
        if gw:
            _validate_ipv4(gw)
            lines.append("      routes:")
            lines.append("        - to: default")
            lines.append(f"          via: {gw}")
        if dns:
            for d in dns:
                _validate_ipv4(str(d))
            lines.append("      nameservers:")
            lines.append(f"        addresses: [{', '.join(str(d) for d in dns)}]")
        return lines

    # Note: this does NOT attempt advanced policy routing. It assumes control has default route,
    # and AVoIP is same-subnet to AMX devices (no gateway) or you handle routing separately.
    lines: List[str] = []
    lines.append("# Generated by DriverTranslator linux/network/nic_setup.py")
    lines.append("network:")
    lines.append("  version: 2")
    lines.append("  renderer: networkd")
    lines.append("  ethernets:")
    lines += iface_block(ctrl_nic, ctrl_cfg)
    if avoip is not None:
        (av_nic, av_cfg) = avoip
        lines += iface_block(av_nic, av_cfg)
    lines.append("")
    return "\n".join(lines)


def write_netplan(path: Path, yaml_text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(yaml_text, encoding="utf-8")
    tmp.replace(path)
    # netplan warns if config permissions are too open
    path.chmod(0o600)


def main() -> int:
    p = argparse.ArgumentParser(description="Configure dual-NIC static IP for DriverTranslator")
    sub = p.add_subparsers(dest="cmd", required=True)

    sub.add_parser("list", help="List NICs (name, mac, ipv4)")

    ap = sub.add_parser("generate-netplan", help="Generate netplan YAML from config JSON")
    ap.add_argument("--config", required=True, help="Path to network_config.json")
    ap.add_argument("--out", default="99-drivertranslator.yaml", help="Output filename (no directory)")

    aap = sub.add_parser("apply-netplan", help="Write netplan file and run netplan apply (requires root)")
    aap.add_argument("--config", required=True, help="Path to network_config.json")
    aap.add_argument("--path", default="/etc/netplan/99-drivertranslator.yaml", help="Netplan file path")

    args = p.parse_args()

    if args.cmd == "list":
        for n in list_nics():
            print(f"{n.name}\t{n.mac}\t{', '.join(n.ipv4) if n.ipv4 else '-'}")
        return 0

    cfg = json.loads(Path(args.config).read_text(encoding="utf-8"))
    nics = list_nics()

    ctrl_match = cfg.get("control", {}).get("match", {})
    ctrl = _match_nic(nics, ctrl_match)
    avoip_cfg = cfg.get("avoip")
    avoip: Optional[Tuple[Nic, Dict[str, Any]]] = None
    if isinstance(avoip_cfg, dict):
        av_match = avoip_cfg.get("match", {})
        av = _match_nic(nics, av_match)
        avoip = (av, avoip_cfg)

    yaml_text = _render_netplan_yaml(
        control=(ctrl, cfg["control"]),
        avoip=avoip,
    )

    if args.cmd == "generate-netplan":
        out = Path(args.out)
        out.write_text(yaml_text, encoding="utf-8")
        print(str(out))
        return 0

    if args.cmd == "apply-netplan":
        if os.geteuid() != 0:
            raise SystemExit("apply-netplan must be run as root (sudo).")
        path = Path(args.path)
        write_netplan(path, yaml_text)
        print(f"Wrote {path}")
        subprocess.check_call(["netplan", "apply"])
        print("netplan apply complete")
        return 0

    raise SystemExit("unknown command")


if __name__ == "__main__":
    raise SystemExit(main())

